### PR TITLE
Independent of SBDownloadingIcon + Constraints for SBDownloadingIcon

### LINKED ISSUE #3: Get the right NSProgress (or ASDProgress)
Getting an NSProgress object for the actual install progress instead of relying on the home screen SBDownloadIcon, which will post a notification only when the view will appear.

### PR DESCRIPTION
**Pull request by RuntimeOverflow**
The progress doesn't sync up anymore with the home screen app icon (this is not my mistake, it is so the circle animation is smooth). Because we're not using the circle animation, should I make them sync up?

### CODE REVIEW

**Comment by lgariv** [comment]
@RuntimeOverflow Tried to use this version for the past few hours, now the notification doesn't post at all.
I used the .deb automatically created in your [releases section](https://github.com/RuntimeOverflow/DownloadBar14/releases). Can you test and confirm if it is working for you with this .deb, and perhaps provide a screen recording of how it works?

**Comment by RuntimeOverflow** [comment]
@lgariv Works perfectly for me (https://streamable.com/t9e07n). I even used the generated release. Possibly an issue with iOS 14?

**Comment by RuntimeOverflow** [comment]
Update: Issue confirmed on an iOS 14 device.

**Comment by RuntimeOverflow** [comment]
@lgariv Sorry for the inconvenience, should be fixed now! (That's what happens when you don't fully test features, it seems to have worked for updating, but not new installs)

**Comment by lgariv** [comment]
Confirm it is now working. Good work man!

**Pull request merged**
