### PR TITLE
Layout Constraints, Parallel Downloading & more! (See Commit History)

### PR DESCRIPTION
**Pull request by RuntimeOverflow**

### CODE REVIEW

**Comment by lgariv** [comment]
Was waiting for your pull request after I saw the first few commits you’ve made😄
I’ve done a little bit of stuff on my local version, so I’ll review it tomorrow and will merge it with the main branch.
Thanks a lot for your effort!

**Comment by lgariv** [comment]
@RuntimeOverflow
- [ ] Which iOS version do you have?
- [ ] Which Xcode command line tools version are you using?
- [x] What SDK version did you compile it with?
- [x] did you use dragon or theos to compile?

**Comment by RuntimeOverflow** [comment]
1. iOS 13.5 (iPhone X)
2. None (Compiling on-device (may switch back to my WSL again, but it is corrupted))
3. iOS 13.5.1 (I don't remember where I got it from)
4. First Dragon but switched back to Theos (because you can't have dragon and theos at the same time on-device and I need to compile other tweaks)

**Comment by lgariv** [comment]
> 1. iOS 13.5 (iPhone X)
> 
> 2. None (Compiling on-device (may switch back to my WSL again, but it is corrupted))
> 
> 3. iOS 13.5.1 (I don't remember where I got it from)
> 
> 4. First Dragon but switched back to Theos (because you can't have dragon and theos at the same time on-device and I need to compile other tweaks)

@RuntimeOverflow Can you upload your compile version? For some reason when I compile it, it crashes when posting the notification. I want to check if this is a compiler bug or a bug in our code

**Comment by RuntimeOverflow** [comment]
@lgariv https://srv-store2.gofile.io/download/ROg3Yq/com.miwix.downloadbar14_1.0.0-74%2Bdebug_iphoneos-arm.deb

**Comment by lgariv** [comment]
@RuntimeOverflow No crash now which is weird, but the progress bar does not load at all which is even weirder...
image

**Comment by RuntimeOverflow** [comment]
@lgariv I need to investigate this because I have the same issue when using other tweaks, but when I use Choicy to disable every other tweak, it works. (I thought this was an issue with Velvet, but it seems not.) Anyway, it worked before (even with other tweaks), so I'll look through the commit history again to find the cause.

**Comment by RuntimeOverflow** [comment]
I have narrowed down the issue. It seems that the progress bar doesn't get added to the view for some reason. Not really sure why it works without any other tweaks.

**Comment by RuntimeOverflow** [comment]
Update: The UIProgressView is NULL, not really sure why.

**Comment by RuntimeOverflow** [comment]
@lgariv Fixed in the new pull request.

**Pull request merged**
